# configuration for objects and agents, add scene as well
task_name: SwipeCard
scene:
  name: Robocasa
  env:
    scene_idx: 0
    layout_idx: 3  # 0-9
    style_idx: 3  # 0-11
    customized_layout: configs/robocasa/customized_layout.yaml 

  primitives:
    - name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.1
        color: [0.5, 0.5, 0.5, 1]
        name: cube
        initial_pose:
          p: [2.95, -3.7, 1.02]
      pos:
        ppos:
          p: [2.95, -3.7, 1.02]
        qpos: [1., 0., 0., 0.43]
        randp_scale: [0, 0, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]
    
objects:
  - name: terminal
    file_path: assets/objects/terminal_annotated/terminal.glb
    annotation_path: assets/objects/terminal_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.0
    visual:
      filename: assets/objects/terminal_annotated/terminal.glb
      scale: [1, 1, 1]
    collision:
      type: nonconvex       
      filename: assets/objects/terminal_annotated/terminal.glb
      scale: [1, 1, 1]
    pos:
      ppos:
        p: [2.95, -2.95, 0.92]
      qpos: [0.5, 0.5, 0.5, 0.5]
      randp_scale: [0.05, 0.05, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    static: true

  - name: card
    file_path: assets/objects/card_annotated/card.glb
    annotation_path: assets/objects/card_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 1  
        dynamic_friction: 1
        restitution: 0.0
    visual:
      filename: assets/objects/card_annotated/card.glb
      scale: [1.0, 1.0, 1.0]   
    collision:
      type: convex             
      filename: assets/objects/card_annotated/card.glb
      scale: [1.0, 1.0, 1.0]
    pos:
      ppos:
        p: [2.85, -3.75, 1.12]
      qpos: [0.0, 0.0, 0.70710678, 0.70710678]
      randp_scale: [0.05, 0.05, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    mass_params:
      mass: 0.005
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.001, 0.001, 0.001]

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [2.55, -3.75, 0.92]
        q: [0.0, 0.0, 0.0]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0, 0]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  - robot_uid: panda-1
    pos:
      ppos:
        p: [2.55, -2.95, 0.92]
        q: [0.0, 0.0, 0.0]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

cameras:
  sensor:
    - uid: head_camera_agent0
      pose:
        type: pose
        params: [[3.58417, -3.77095, 1.66417], [0.236012, -0.270208, 0.0685053, 0.93091]]
      width: 2048
      height: 2048
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_agent1
      pose:
        type: pose
        params: [[3.13473, -3.43111, 1.68784], [0.00612763, 0.405466, 0.00271818, -0.914085]]
      width: 2048
      height: 2048
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_global
      pose:
        type: pose
        params: [[3.45596, -2.78785, 1.52775], [0.249327, 0.196941, 0.0518642, -0.946763]]
      width: 2048
      height: 2048
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - uid: render_camera
      pose:
        type: pose
        params: [[3.31788, -3.59214, 1.74821], [0.239565, -0.274649, 0.0708612, 0.928523]]
      width: 2048
      height: 2048
      fov: 1.5707963268
      near: 0.1
      far: 10
