defaults:
  - default_task

name: 1a_suction_card_3d
agent_num: 1

point_shape: &point_shape [1024, 3]
action_shape: &action_shape [8]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    pointcloud:
      shape: *point_shape
      type: point_cloud
    agent_pos:
      shape: *action_shape
      type: low_dim
  action:
    shape: *action_shape

dataset:
  # _target_: diffusion_policy.dataset.dataset3d.Dataset3D
  _target_: diffusion_policy.dataset.dataset3d_mem.Dataset3D
  dataset_path: data/suction_card_pointcloud.h5
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  input_meta: 
    obs:
      pointcloud: *point_shape
      agent_pos_0: *action_shape
    action_0: *action_shape
  seperate_action: False
  only_xyz: True
  
