task_name: PickPokeball
scene:
  name: Table
  assets: 
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0, 0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos: 
        ppos:
          p: [-0.12, 0., -0.9196429]
          q: [0., 0., 1.5707963268]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      scale: [4.375, 4.375, 1.75]
  env:
    floor_width: 100

objects:
  - name: pokeball
    file_path: assets/objects/pokeball_annotated/pokeball.glb
    annotation_path: assets/objects/pokeball_annotated/model_data.json
    visual:
      filename: assets/objects/pokeball_annotated/pokeball.glb
      scale: [0.04, 0.04, 0.04]
    collision:
      type: convex
      filename: assets/objects/pokeball_annotated/pokeball.glb
      scale: [0.04, 0.04, 0.04]
    pos:
      ppos:
        p: [0.2, 0.2, 0.]
        q: [0., 0., 0.]
      qpos: [0.7071, 0.7071, 0., 0.]
      randp_scale: [0.2, 0.2, 0.]
      randq_scale: [0., 0., 0., 0.]
    mass_params:
      mass: 2
      cmass_local_pose: [0., 0., 0.]
      inertia: [0, 0, 0]
    
agents:
  - 
    robot_uid: panda-0
    pos:
      ppos:
        p: [-0.3, 0., 0.]
        q: [0., 0., 0.]
      qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634, 0.04, 0.04]
      # qpos: [0., 0.3926990817, 0., -1.9634954085, 0., 2.3561944902, 0.7853981634]
      randp_scale: [0., 0., 0.]
      randq_scale: [0., 0., 0., 0., 0., 0., 0., 0., 0.]
      # randq_scale: [0., 0., 0., 0., 0., 0., 0.]

cameras:
  sensor:
    - 
      uid: head_camera
      pose:
        type: look_at
        params: [[0.6, 0.6, 0.4], [0.0, 0.0, 0.2]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - 
      uid: render_camera
      pose:
        type: look_at
        params: [[0.6, 0.6, 0.4], [0.0, 0.0, 0.2]]
      width: 256
      height: 256
      fov: 1
      near: 0.01
      far: 100
