# configuration for objects and agents, add scene as well
task_name: PlaceBadminton

scene:
  name: Table
  primitives:
    - name: cubeA
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.06
        color: [0.5, 0.5, 0.5, 1]
        name: cubeA
        body_type: static
        initial_pose:
          p: [-0.0, -0., 0.03]
      pos:
        ppos:
          p: [-0.0, -0., 0.03]
          q: [0., 0., 1.5707963268]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cubeB
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.06
        color: [0.5, 0.5, 0.5, 1]
        name: cubeB
        body_type: static
        initial_pose:
          p: [0.3, -0.3, 0.03]
      pos:
        ppos:
          p: [0.3, -0.3, 0.03]
          q: [0., 0., 1.5707963268]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]

    - name: cubeC
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.06
        color: [0.5, 0.5, 0.5, 1]
        name: cubeC
        body_type: static
        initial_pose:
          p: [-0.3, -0., 0.03]
      pos:
        ppos:
          p: [-0.3, -0., 0.03]
          q: [0., 0., 1.5707963268]
        qpos: [1., 0., 0., 0.]
        randp_scale: [0., 0., 0.]
        randq_scale: [0., 0., 0., 0.]
      
  env:
    floor_width: 100
  assets:
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0.0, 0.0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos:
        ppos:
          p: [-0.12, 0.0, -0.9196429]
          q: [0.0, 0.0, 1.5707963268]
        randp_scale: [0.0, 0.0, 0.0]
        randq_scale: [0.0, 0.0, 0.0, 0.0]
      scale: [4.375, 4.375, 1.75]

objects:
  - name: badminton
    file_path: assets/objects/badminton_annotated/badminton.glb
    annotation_path: assets/objects/badminton_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.0
    visual:
      filename: assets/objects/badminton_annotated/badminton.glb
      scale: [1, 1, 1]
    collision:
      type: nonconvex       
      filename: assets/objects/badminton_annotated/badminton.glb
      scale: [1, 1, 1]
    pos:
      ppos:
        p: [0.3, -0.3, 0.2]
      qpos: [0.5, 0.5, 0.5, 0.5]
      # qpos: [0.0000, 0.7071, 0.0000, -0.7071]
      randp_scale: [0.03, 0.03, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    mass_params:
      mass: 0.1
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.01, 0.01, 0.01]

  - name: barrel
    file_path: assets/objects/barrel_annotated/barrel.glb
    annotation_path: assets/objects/barrel_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 1  
        dynamic_friction: 1
        restitution: 0.0
    visual:
      filename: assets/objects/barrel_annotated/barrel.glb
      scale: [1.0, 1.0, 1.0]   
    collision:
      type: nonconvex             
      filename: assets/objects/barrel_annotated/barrel.glb
      scale: [1.0, 1.0, 1.0]
    pos:
      ppos:
        p: [-0.3, 0., 0.06]
      qpos: [0.5, 0.5, -0.5, -0.5]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    mass_params:
      mass: 0.5
      cmass_local_pose: [0., 0., 0.]
      inertia: [0., 0., 0.]

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [0.0, -0.5, 0.0]
        q: [0.0, 0.0, 0.0]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  - robot_uid: panda-1
    pos:
      ppos:
        p: [0.0, 0.4, 0.0]
        q: [0.0, 0.0, 0.0]
      # qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0.0, 0.0]
      randp_scale: [0.0, 0.0, 0.0]
      # randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

cameras:
  sensor:
    - uid: head_camera_agent0
      pose:
        type: look_at
        params: [[0.9, -0.4, 0.4], [0.0, 0.0, 0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_agent1
      pose:
        type: look_at
        params: [[1.0, 0.8, 0.4], [0.0, 0.0, -0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_global
      pose:
        type: look_at
        params: [[0.8, -0.3, 0.4], [0.0, 0.0, 0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - uid: render_camera
      pose:
        type: look_at
        params: [[1.2, -0.6, 0.2], [0.0, 0.0, 0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
