# configuration for objects and agents, add scene as well
task_name: SwipeCard

scene:
  name: Table
  env:
    floor_width: 100
  assets:
    - name: table
      file_path: assets/scenes/table/table.glb
      collision:
        type: box
        pos:
          p: [0.0, 0.0, 0.45982145]
          half_size: [3.0225, 1.51125, 0.45982145]
      pos:
        ppos:
          p: [-0.12, 0.0, -0.9196429]
          q: [0.0, 0.0, 1.5707963268]
        randp_scale: [0.0, 0.0, 0.0]
        randq_scale: [0.0, 0.0, 0.0, 0.0]
      scale: [4.375, 4.375, 1.75]
  primitives:
    - name: cube
      builder: mani_skill.utils.building.actors.build_cube
      params:
        half_size: 0.1
        color: [0.5, 0.5, 0.5, 1]
        name: cube
        initial_pose:
          p: [0.4, -0.35, 0.1]
      pos:
        ppos:
          p: [0.4, -0.35, 0.1]
        qpos: [1., 0., 0., 0.43]
        randp_scale: [0, 0, 0.]
        randq_scale: [0., 0., 0., 0.]
        random_quaternions: [1, 1, 0]

objects:
  - name: terminal
    file_path: assets/objects/terminal_annotated/terminal.glb
    annotation_path: assets/objects/terminal_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 0.3
        dynamic_friction: 0.3
        restitution: 0.0
    visual:
      filename: assets/objects/terminal_annotated/terminal.glb
      scale: [1, 1, 1]
    collision:
      type: nonconvex       
      filename: assets/objects/terminal_annotated/terminal.glb
      scale: [1, 1, 1]
    pos:
      ppos:
        p: [0.4, 0.4, 0]
      qpos: [0.5, 0.5, 0.5, 0.5]
      randp_scale: [0.05, 0.05, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    static: true

  - name: card
    file_path: assets/objects/card_annotated/card.glb
    annotation_path: assets/objects/card_annotated/model_data.json
    material:
      type: sapien.pysapien.physx.PhysxMaterial
      params:
        static_friction: 1  
        dynamic_friction: 1
        restitution: 0.0
    visual:
      filename: assets/objects/card_annotated/card.glb
      scale: [1.0, 1.0, 1.0]   
    collision:
      type: convex             
      filename: assets/objects/card_annotated/card.glb
      scale: [1.0, 1.0, 1.0] 
    pos:
      ppos: 
        p:  [0.29272, -0.352721, 0.200845] # [0.40, -0.4, 0.2]
      qpos: [0.0, 0.0, 0.70710678, 0.70710678] # [0.007, 0.004, 0.70, 0.70]
      randp_scale: [0.01, 0.01, 0.0] # [0.055, 0.055, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0]
    mass_params:
      mass: 0.005
      cmass_local_pose: [0., 0., 0.]
      inertia: [0.001, 0.001, 0.001]

agents:
  - robot_uid: panda-0
    pos:
      ppos:
        p: [0.0, -0.4, 0.0]
        q: [0.0, 0.0, 0.0]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  - robot_uid: panda-1
    pos:
      ppos:
        p: [0.0, 0.4, 0.0]
        q: [0.0, 0.0, 0.0]
      qpos: [0.0, 0.3926990817, 0.0, -1.9634954085, 0.0, 2.3561944902, 0.7853981634, 0.04, 0.04]
      randp_scale: [0.0, 0.0, 0.0]
      randq_scale: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

cameras:
  sensor:
    - uid: head_camera_agent0
      pose:
        type: look_at
        params: [[0.85, 0., 0.3], [0.0, -0.3, 0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_agent1
      pose:
        type: look_at
        params: [[1, 0., 0.5], [0.0, 0.0, 0.]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
    - uid: head_camera_global
      pose:
        type: look_at
        params: [[1, 0., 0.5], [0.0, 0., 0.]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
  human_render:
    - uid: render_camera
      # pose:
      #   type: pose
      #   params: [[0.868396, 1.09695, 0.703708], [0.454605, 0.234498, 0.125406, -0.85007]]
      # width: 256
      # height: 256
      # fov: 1.0
      # near: 0.01
      # far: 100
      pose:
        type: look_at
        params: [[1.2, 0., 0.694811], [0.0, 0.0, 0.1]]
      width: 256
      height: 256
      fov: 1.5707963268
      near: 0.1
      far: 10
